services:
  frontend:
    build:
      context: ./killigraphy
      dockerfile: Dockerfile
    volumes:
      - ./killigraphy:/app
      - /app/node_modules
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8085/api
    depends_on:
      - backend
    networks:
      - killigraphy-network

  backend:
    build:
      context: ./killigraphy_back_end
      dockerfile: Dockerfile
    volumes:
      - ./killigraphy_back_end:/app
      - /app/node_modules
    ports:
      - "8085:8085"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/killigraphy
      - JWT_SECRET=8fc07a7191073fe335b82cfca2027daf1c86e4645bd3606bce5f92e6e53ba61887978747a0c372f2582dc1c53980ee01e7e09e1a2e117254e4c9254c031449656f1e534f5435f676eb2e00ead3e5d973927344ae54e079f61e6e2279f5f837f171eb2250b173bbda143857aed8d49428685772df9e75d9bfdc6347595eeeba37ff54e80dd002d6c098b705585a66718992ef11579041aac98e6098b9b1919bdf4d3b85e083ac64027b706c93440f8dbafb3c34b1ff6ef23aa6f96d3f9cf695544743541e59ece4c2e75992d7e226428c4f2bdb3f0182d666f0c54c9b974c92623bd13f7e3281d2d0e9a8c6348fa91104e81c0dbace97fcf7e9ad425fe80409bd
      - IMAGEKIT_PUBLIC_KEY=public_ESXnVnzPIC6WUaW0z5wXOrfEt78=
      - IMAGEKIT_PRIVATE_KEY=private_Rc9sxzaXhEjCdUKdr55Idjy9Brw=
      - IMAGEKIT_URL_ENDPOINT=https://ik.imagekit.io/killigraphy
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GMAIL_PASS=lkhrlziyefeycmfe
      - GMAIL_USER=bladehsr.2407@gmail.com
    networks:
      - killigraphy-network

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - killigraphy-network

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - killigraphy-network

volumes:
  mongo-data:
  redis_data:


networks:
  killigraphy-network:
    driver: bridge
